### ISSUE TITLE
GSSoC24: Dark mode availability (level 3)

### ISSUE THREAD

**Issue by swrno** [Shashank2104125/nyayaSadhak#13]
Implement a dark theme. Feel free to go through tailwind docs: https://tailwindcss.com/docs/dark-mode

**Comment by rahulpoonia29** [comment]
I would like to work on the issue under GSsoC'

**Comment by mukulpythondev** [comment]
@Swarnendu0123  I am highly interested in this issue and i wanna work on it. Please assign to me.

**Comment by swrno** [comment]
Yes @mukulpythondev @rahulpoonia29 both of you can work on the issue!
We are not going to assign the issues to anyone. We will give priority, whoever would create the PR first.
