### ISSUE TITLE
GSSoC24: Write a Installation.md file (level 2)

### ISSUE THREAD

**Issue by swrno** [Shashank2104125/nyayaSadhak#14]
Currently we don't have any installation.md file. The issue is aiming to fix that.
- create a folder named `docs` in root dir.
- write the whole process to setup frontend and backend. Attach screenshots also.
- link that file to readme.md in the `setup` section
- raise a PR

**Comment by krishna-singha** [comment]
Please assign it to me. I can fix this issue @GSSoC'24
